apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: filepath-deployment
  name: backups-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-hostpath-sc
  volumeMode: Filesystem
