apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: volumeinjector-deployment
  name: volumeinjector-deployment
  namespace: volumeinjector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volumeinjector-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: volumeinjector-deployment
    spec:
      volumes:
      - name: secrets
        secret:
          secretName: volumeinjector-secret
      containers:
      - image: volume_injector:latest
        imagePullPolicy: Never
        command:
        - /app/bin/volume_injector
        - "injector"
        name: volumeinjector
        resources: {}
        volumeMounts:
          - name: secrets
            readOnly: true
            mountPath: "/tmp/k8s-webhook-server/serving-certs/"
status: {}
