apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: volumeinjector-adapter-injector
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: ${CA_BUNDLE}
    service:
      name: volumeinjector-service
      namespace: volumeinjector
      path: /mutate--v1-pod
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: volumeinjector.leonardoce.io
  namespaceSelector: {}
  objectSelector:
    matchExpressions:
    - key: cnpg.io/cluster
      operator: Exists
    - key: cnpg.io/instanceName
      operator: Exists
    - key: cnpg.io/podRole
      operator: Exists
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
