apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: filepath-service
  name: filepath-service
  namespace: filepath
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: filepath-deployment
status:
  loadBalancer: {}
