apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: volumeinjector-service
  name: volumeinjector-service
  namespace: volumeinjector
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: volumeinjector-deployment
status:
  loadBalancer: {}
